openapi: 3.0.1
info:
  description: This is a default server
  title: Hello World
  version: 1.0.0
servers:
- url: https://localhost:8080/v1
- url: http://localhost:8080/v1
tags:
- description: Basic hello world api
  name: hello-world
paths:
  /hello:
    get:
      operationId: hello_world
      responses:
        "200":
          content:
            '*/*':
              schema:
                default: Hello World
                type: string
          description: Returns the greeting.
      summary: Returns a string
      tags:
      - hello-world
      x-openapi-router-controller: openapi_server.controllers.hello_world_controller
components:
  schemas: {}
x-original-swagger-version: "2.0"
